# Generated by Django 4.0.5 on 2022-06-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('imagen', models.FileField(upload_to='static/img/')),
            ],
        ),
    ]
