# Generated by Django 4.0.5 on 2022-06-29 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Direccion'),
            preserve_default=False,
        ),
    ]
