# Generated by Django 4.0.5 on 2022-07-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cliente_direccion_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('idProducto', models.CharField(max_length=20, null=True, verbose_name='Id_Producto')),
                ('rut', models.CharField(max_length=20, null=True, verbose_name='Rut')),
                ('estado', models.CharField(max_length=20, null=True, verbose_name='Estado_Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.CharField(max_length=4, null=True, verbose_name='Stock'),
        ),
    ]
